# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DEM_information.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InformationDialog(object):
    def setupUi(self, InformationDialog):
        InformationDialog.setObjectName("InformationDialog")
        InformationDialog.resize(449, 620)
        self.widget = QtWidgets.QWidget(InformationDialog)
        self.widget.setGeometry(QtCore.QRect(40, 20, 326, 448))
        self.widget.setObjectName("widget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget)
        self.formLayout_2.setContentsMargins(0, 10, 0, 10)
        self.formLayout_2.setHorizontalSpacing(10)
        self.formLayout_2.setVerticalSpacing(20)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.textType = QtWidgets.QTextBrowser(self.widget)
        self.textType.setObjectName("textType")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textType)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.textBandNum = QtWidgets.QTextBrowser(self.widget)
        self.textBandNum.setObjectName("textBandNum")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textBandNum)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 0, -1, 0)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.textName = QtWidgets.QTextBrowser(self.widget)
        self.textName.setObjectName("textName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textName)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.textExtent = QtWidgets.QTextBrowser(self.widget)
        self.textExtent.setObjectName("textExtent")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textExtent)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.formLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setVerticalSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 2, 1, 1)
        self.textMax = QtWidgets.QTextBrowser(self.widget)
        self.textMax.setObjectName("textMax")
        self.gridLayout_2.addWidget(self.textMax, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.textHeight = QtWidgets.QTextBrowser(self.widget)
        self.textHeight.setObjectName("textHeight")
        self.gridLayout_2.addWidget(self.textHeight, 1, 3, 1, 1)
        self.textWidth = QtWidgets.QTextBrowser(self.widget)
        self.textWidth.setObjectName("textWidth")
        self.gridLayout_2.addWidget(self.textWidth, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.textMin = QtWidgets.QTextBrowser(self.widget)
        self.textMin.setObjectName("textMin")
        self.gridLayout_2.addWidget(self.textMin, 2, 3, 1, 1)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_2)

        self.retranslateUi(InformationDialog)
        QtCore.QMetaObject.connectSlotsByName(InformationDialog)

    def retranslateUi(self, InformationDialog):
        _translate = QtCore.QCoreApplication.translate
        InformationDialog.setWindowTitle(_translate("InformationDialog", "DEM 基本信息"))
        self.label_7.setText(_translate("InformationDialog", "栅格类型"))
        self.label_8.setText(_translate("InformationDialog", "波段个数"))
        self.label.setText(_translate("InformationDialog", "名称"))
        self.label_2.setText(_translate("InformationDialog", "范围"))
        self.label_6.setText(_translate("InformationDialog", "高程最大值"))
        self.label_3.setText(_translate("InformationDialog", "宽度"))
        self.label_5.setText(_translate("InformationDialog", "高程最大值"))
        self.label_4.setText(_translate("InformationDialog", "高度"))
