# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DEM_information.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InformationDialog(object):
    def setupUi(self, InformationDialog):
        InformationDialog.setObjectName("InformationDialog")
        InformationDialog.resize(449, 620)
        self.verticalLayout = QtWidgets.QVBoxLayout(InformationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 10, -1, 10)
        self.gridLayout_3.setSpacing(20)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_4.setHorizontalSpacing(25)
        self.gridLayout_4.setVerticalSpacing(20)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(InformationDialog)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.textName = QtWidgets.QTextBrowser(InformationDialog)
        self.textName.setObjectName("textName")
        self.gridLayout_4.addWidget(self.textName, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(InformationDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.textExtent = QtWidgets.QTextBrowser(InformationDialog)
        self.textExtent.setObjectName("textExtent")
        self.gridLayout_4.addWidget(self.textExtent, 1, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 5)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 0, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(InformationDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.textMax = QtWidgets.QTextBrowser(InformationDialog)
        self.textMax.setObjectName("textMax")
        self.gridLayout_2.addWidget(self.textMax, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(InformationDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(InformationDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.textHeight = QtWidgets.QTextBrowser(InformationDialog)
        self.textHeight.setObjectName("textHeight")
        self.gridLayout_2.addWidget(self.textHeight, 1, 3, 1, 1)
        self.textWidth = QtWidgets.QTextBrowser(InformationDialog)
        self.textWidth.setObjectName("textWidth")
        self.gridLayout_2.addWidget(self.textWidth, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(InformationDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.textMin = QtWidgets.QTextBrowser(InformationDialog)
        self.textMin.setObjectName("textMin")
        self.gridLayout_2.addWidget(self.textMin, 2, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(InformationDialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.textType = QtWidgets.QTextBrowser(InformationDialog)
        self.textType.setObjectName("textType")
        self.gridLayout_3.addWidget(self.textType, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(InformationDialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.textBandNum = QtWidgets.QTextBrowser(InformationDialog)
        self.textBandNum.setObjectName("textBandNum")
        self.gridLayout_3.addWidget(self.textBandNum, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)

        self.retranslateUi(InformationDialog)
        QtCore.QMetaObject.connectSlotsByName(InformationDialog)

    def retranslateUi(self, InformationDialog):
        _translate = QtCore.QCoreApplication.translate
        InformationDialog.setWindowTitle(_translate("InformationDialog", "DEM 基本信息"))
        self.label.setText(_translate("InformationDialog", "名称"))
        self.label_2.setText(_translate("InformationDialog", "范围"))
        self.label_6.setText(_translate("InformationDialog", "高程最大值"))
        self.label_3.setText(_translate("InformationDialog", "宽度"))
        self.label_5.setText(_translate("InformationDialog", "高程最大值"))
        self.label_4.setText(_translate("InformationDialog", "高度"))
        self.label_7.setText(_translate("InformationDialog", "栅格类型"))
        self.label_8.setText(_translate("InformationDialog", "波段个数"))
