# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InformationDialog(object):
    def setupUi(self, InformationDialog):
        InformationDialog.setObjectName("InformationDialog")
        InformationDialog.resize(485, 326)
        self.widget = QtWidgets.QWidget(InformationDialog)
        self.widget.setGeometry(QtCore.QRect(20, 20, 441, 281))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.textName = QtWidgets.QTextBrowser(self.widget)
        self.textName.setObjectName("textName")
        self.horizontalLayout_2.addWidget(self.textName)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignLeft)
        self.textExtent = QtWidgets.QTextBrowser(self.widget)
        self.textExtent.setObjectName("textExtent")
        self.horizontalLayout.addWidget(self.textExtent)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignLeft)
        self.textWidth = QtWidgets.QTextBrowser(self.widget)
        self.textWidth.setObjectName("textWidth")
        self.horizontalLayout_3.addWidget(self.textWidth)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.textHeight = QtWidgets.QTextBrowser(self.widget)
        self.textHeight.setObjectName("textHeight")
        self.horizontalLayout_3.addWidget(self.textHeight)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 4)
        self.horizontalLayout_3.setStretch(2, 2)
        self.horizontalLayout_3.setStretch(3, 4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5, 0, QtCore.Qt.AlignLeft)
        self.textMax = QtWidgets.QTextBrowser(self.widget)
        self.textMax.setObjectName("textMax")
        self.horizontalLayout_4.addWidget(self.textMax)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.textMin = QtWidgets.QTextBrowser(self.widget)
        self.textMin.setObjectName("textMin")
        self.horizontalLayout_4.addWidget(self.textMin)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 4)
        self.horizontalLayout_4.setStretch(2, 2)
        self.horizontalLayout_4.setStretch(3, 4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8, 0, QtCore.Qt.AlignLeft)
        self.textType = QtWidgets.QTextBrowser(self.widget)
        self.textType.setObjectName("textType")
        self.horizontalLayout_5.addWidget(self.textType)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9, 0, QtCore.Qt.AlignLeft)
        self.textBandNum = QtWidgets.QTextBrowser(self.widget)
        self.textBandNum.setObjectName("textBandNum")
        self.horizontalLayout_6.addWidget(self.textBandNum)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.retranslateUi(InformationDialog)
        QtCore.QMetaObject.connectSlotsByName(InformationDialog)

    def retranslateUi(self, InformationDialog):
        _translate = QtCore.QCoreApplication.translate
        InformationDialog.setWindowTitle(_translate("InformationDialog", "Dialog"))
        self.label.setText(_translate("InformationDialog", "<html><head/><body><p>名称</p></body></html>"))
        self.label_2.setText(_translate("InformationDialog", "范围"))
        self.label_3.setText(_translate("InformationDialog", "宽度"))
        self.label_4.setText(_translate("InformationDialog", "高度"))
        self.label_5.setText(_translate("InformationDialog", "高程最大值"))
        self.label_7.setText(_translate("InformationDialog", "<html><head/><body><p align=\"center\">高程最大值</p></body></html>"))
        self.label_8.setText(_translate("InformationDialog", "栅格类型"))
        self.label_9.setText(_translate("InformationDialog", "波段个数"))
